version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=POSTGRES_DB
      - POSTGRES_USER=POSTGRES_USER
      - POSTGRES_PASSWORD=POSTGRES_PASSWORD
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - POSTGRES_DATA_PATH:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    command: postgres -c 'listen_addresses=*'

    networks:
      - localai_ai_network

volumes:
  pg-data:

networks:
  localai_ai_network:
    external: true
